### PR TITLE
Fix json and text uploads: don't parse bodies with input encoding of */*

### LINKED ISSUE #4026: Uploading plaintext to the PDS fails.
**Describe the bug**

When uploading a plaintext file to the PDS (i.e. a 1mb string) the upload fails, either with a "PayloadTooLargeError" or an "InternalServerError."
 
**To Reproduce**

Run the code below:

```typescript
import AtpAgent from "@atproto/api";

const agent = new AtpAgent({
  service: "https://bsky.social/",
});

await agent.login({
  identifier: "ID",
  password: "PASSWORD",
});

const longString = "a".repeat(1024 * 1024); // 1 MB of 'a's

const assetUploadResponse = await agent.uploadBlob(longString, {
  encoding: "text/plain"
});

console.log("Asset upload response:", assetUploadResponse);
```

**Expected behavior**

The file is uploaded and available as an `application/octet-stream`.

**Additional context**

This happens on both the selfhosted PDS and Bsky PDS instances. When encoding the file as utf-8 it uploads fine, somehow.

### PR DESCRIPTION
**Pull request by devinivy**
Uploads of json and text content were failing, as xrpc-server would consume the request body by attempting to parse them.  This step could also apply lower text/json-specific size limitations.  This has been addressed by skipping body parsing when the lexicon's input encoding is `*/*`, which indicates that the handler accepts any content-type and will determine how to process the body.

Resolves #4026

### CODE REVIEW

File: packages/xrpc-server/src/util.ts [hunk 1]
```diff
@@ -164,7 +164,9 @@ export function createInputVerifier(
       )
     }
 
-    await bodyParser(req, res)
+    if (input.encoding !== ENCODING_ANY) {
+      await bodyParser(req, res)
```
Comment (matthieusieben) [inline packages/xrpc-server/src/util.ts:155]: We could improve memory usage by not creating a `bodyParser` at all!

**Review by matthieusieben — APPROVED** [review]
Awesome! Left a small nit but looks great!
