### PR TITLE
Set COEP header to "unsafe-none" when hcaptcha is enabled

### LINKED ISSUE #3625: Unable to configure hCaptcha on oAuth login
**Describe the bug**

Due to strong security headers:
```
  res.setHeader('Cross-Origin-Embedder-Policy', 'credentialless')
  res.setHeader('Cross-Origin-Resource-Policy', 'same-origin')
  res.setHeader('Cross-Origin-Opener-Policy', 'same-origin')
```
in `packages/oauth/oauth-provider/src/output/send-web-page.ts` the hCapctha iframe is not allowed to load

**To Reproduce**

1. Configure hCaptcha in pds .env
2. Open a oAuth flow
3. Fill in the signup form
4. When the iFrame tries to load, it gets blocked by chrome/Firefox

**Expected behavior**

hCaptcha should add the `Cross-Origin-Resource-Policy: cross-origin` header, or the atproto code should use a less strict policy

**Details**

- Operating system: MacOS 15.4 Beta (24E5222f)
- Chrome: 134.0.6998.45 (Official Build) (arm64) 

**Additional context**

Image
Image

### PR DESCRIPTION
**Pull request by matthieusieben**
- Removes un-necessary CSP directives (making CSP header shorted)
- Optimize backend injected data by generating fewer <script> tags (alloiwng to make CSP header shorter)
- Enables configuration of COEP, CORP & COOP headers in HTML responses
- Fixes issue in HTML class that would cause the output to sometimes be empty (preventing proper generation CSP headers)
- Disables pre-loading of assets that are referenced in the page (they were loaded twice)
- Improve type safety in front-end code by asserting backend vars are injected

Fixes #3625

### CODE REVIEW

File: packages/oauth/oauth-provider/src/lib/html/html.ts [hunk 1]
```diff
@@ -49,11 +49,7 @@ export class Html implements Iterable<string> {
 
   *[Symbol.iterator](): IterableIterator<string> {
     for (const fragment of this.#fragments) {
-      if (typeof fragment === 'string') {
-        yield fragment
-      } else {
-        yield* fragment
-      }
+      yield String(fragment)
```
Comment (matthieusieben) [inline packages/oauth/oauth-provider/src/lib/html/html.ts:52]: This change enables the `toString()` optimization from this class to be used. For some reason (which I did not take time to debug any further), the previous behavior could cause this `HTML` instance to become "empty" after it was read once.

File: packages/oauth/oauth-provider/src/assets/asset.ts [hunk 2]
```diff
@@ -1,9 +1,8 @@
 import type { Readable } from 'node:stream'
+import type { ManifestItem } from '@atproto-labs/rollup-plugin-bundle-manifest'
 
 export type Asset = {
   url: string
-  type?: string
-  isEntry: boolean
-  sha256: string
+  item: ManifestItem
```
Comment (matthieusieben) [inline packages/oauth/oauth-provider/src/assets/asset.ts:6]: The `AssetRef` abstraction used in other parts of the code no longer need an `sha256` (was incorrectly used in CSP code). Exposing the full `ManifestItem` here allows for more control (e.g. generating `<link rel="preload" />` of scripts that are dynamically imported).

File: packages/oauth/oauth-provider/src/output/send-web-page.ts [hunk 3]
```diff
@@ -1,82 +1,51 @@
...
     const hash = createHash('sha256').update(asset.toString()).digest('base64')
     return `'sha256-${hash}'`
   } else {
-    return `'sha256-${asset.sha256}'`
+    // External assets are referenced by their full url
+    if (asset.url.startsWith('https:')) return asset.url as `https:${string}`
+    if (asset.url.startsWith('http:')) return asset.url as `http:${string}`
+
+    // Internal assets are served from the same origin
+    return `'self'`
```
Comment (matthieusieben) [inline packages/oauth/oauth-provider/src/output/send-web-page.ts:49]: Bug fix. Specifying the `sha256-` hash of a script that is loaded through `<script src="url"></script>` makes no sense.

File: packages/oauth/oauth-provider/src/output/output-manager.ts [hunk 4]
```diff
@@ -44,40 +58,43 @@ export class OutputManager {
...
+    this.csp = mergeCsp(
+      BASE_CSP,
+      customization?.hcaptcha ? HCAPTCHA_CSP : undefined,
+    )
+    // Because we are loading avatar images from external sources, that might
+    // not have CORP headers set, we need to use at least "credentialless".
+    this.coep = customization?.hcaptcha
+      ? // https://github.com/hCaptcha/react-hcaptcha/issues/259
+        // @TODO Remove the use of `unsafeNone` once the issue above is resolved
+        CrossOriginEmbedderPolicy.unsafeNone
```
Comment (matthieusieben) [inline packages/oauth/oauth-provider/src/output/output-manager.ts:96]: This is the heart of this PR

**Review by devinivy — APPROVED** [review]
