### PR TITLE
Fix Tap generating invalid URLs

### LINKED ISSUE #4476: @atproto/tap incorrectly constructs URLs for API requests
**Describe the bug**

The `@atproto/tap` package constructs invalid URLs for API requests

**To Reproduce**

1. Create a client: `const tap = new Tap("http://localhost:2480/")`
2. Try adding a repo: `await tap.addRepos(['did:plc:5w4eqcxzw5jv5qfnmzxcakfy'])`

**Expected behavior**

The repository for the DID should be added to Tap.

**Actual behavior**

An error is thrown with the message `Failed to add repos: Not Found`, the Tap server logs show:
```
tap-1  | {"time":"2025-12-20T20:07:39.420916216Z","id":"","remote_ip":"172.22.0.1","host":"localhost:2480","method":"POST","uri":"//repos/add","user_agent":"node","status":404,"error":"code=404, message=Not Found","latency":718542,"latency_human":"718.542µs","bytes_in":45,"bytes_out":24}
```

Note the `//repos/add` as the `uri` in the request? This appears to be because of the trailing slash in the url passed to the `Tap` constructor. Removing the trailing slash fixes the issue.

**Details**

- Operating system: MacOS Sequoia 15.7 (24G222) arm64
- Node version: v22.14.0

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
Fixes #4476, needs a changeset. cc @dholms

### CODE REVIEW

File: packages/tap/src/client.ts [hunk 1]
```diff
@@ -10,7 +10,10 @@ export interface TapConfig {
 export class Tap {
   url: string
   private adminPassword?: string
-  private authHeader?: string
+  private authHeader?: string\
```
Comment (ThisIsMissEm) [inline packages/tap/src/client.ts]:
```suggestion
  private authHeader?: string
```

File: packages/tap/src/client.ts [hunk 2]
```diff
@@ -12,6 +12,9 @@ export class Tap {
   private adminPassword?: string
   private authHeader?: string
 
+  private addReposUrl: URL
+  private removeReposUrl: Url
```
Comment (ThisIsMissEm) [inline packages/tap/src/client.ts]:
```suggestion
  private removeReposUrl: URL
```
